# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c20133aac5164e75311f2b207d1c1cf677df5e746314fb327d0a306ad7ba3906cf23a1baab388a715e18a7d3912cd3c16fd10929a6640dab2be03241df5d5ed4

test:
  secret_key_base: f928b442723c3e1715893cce46ca49b8698ef4191e0d7b1bf62f12813d781b0625ef859ed3799f189847c2d1168acaf9bc64b63499032a6c31f79bc306d17e77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
